name: Generate ASCII Artwork

on: 
  push:
    branches:
    - main
  workflow_dispatch: 

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Listing files
        run: ls -altr
      - name: Executing script to install cowsay
        run: |
            chmod +x .github/workflows/ascii.sh
            .github/workflows/ascii.sh
      
