---
name: Generate ASCII Artwork
on:
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build_job_1:
    name: Build Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Install cowsay program
        run: sudo apt-get -y install cowsay
      - name: Execute cowsay command
        run: cowsay -f dragon "Run for ever as I'm DRAGON" >> dragon.txt
      - name: Upload dragon text file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-artifact
          path: dragon.txt
  test_job_2:
    needs: build_job_1
    name: Test Job 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dragon-artifact
      - name: Test file exists or not
        run: grep -i dragon dragon.txt
  deploy_job_3:
    needs: test_job_2
    name: Deploy Job 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dragon-artifact
      - name: Read file
        run: cat dragon.txt
      - name: Deploy
        run: echo "Deploying .... "
