name: OS Details
on: push
jobs:
  os_details:
    name: OS Details
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
     
    - name: os-details
      run: |
        cat /etc/os-release
        ls -altr
        cat README.md
