name: OS Details
on: push
jobs:
  os_details:
    name: OS Details
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
     
    - name: os-details
      run: cat /etc/os-release

    - name: list files
      run: ls

    - name: Read file
      run: cat README.md
