name: OS Details
on: push
jobs:
  os_details:
    name: os_details
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
     
    - name: os-details
      run: cat /etc/os-release
